### ISSUE TITLE
kKFAPIClientErrorDomain, can't start streaming 

### ISSUE THREAD

**Issue by BurningBird** [Kickflip/kickflip-ios-example#13]
2015-03-26 23:40:35:115 Kickflip[589:807] Error pre-fetching new user: Error Domain=kKFAPIClientErrorDomain Code=105 "The operation couldn’t be completed. (kKFAPIClientErrorDomain error 105.)" UserInfo=0x17026c980 {success=false, reason='NoneType' object has no attribute '__getitem__'}
2015-03-26 23:40:35:117 Kickflip[589:807] Error fetching all streams: Error Domain=kKFAPIClientErrorDomain Code=105 "The operation couldn’t be completed. (kKFAPIClientErrorDomain error 105.)" UserInfo=0x17407e800 {success=false, reason='NoneType' object has no attribute '__getitem__'}
2015-03-26 23:40:35:117 Kickflip[589:807] Error fetching all streams: Error Domain=kKFAPIClientErrorDomain Code=105 "Fetch an active user first" UserInfo=0x170274740 {NSLocalizedDescription=Fetch an active user first}
2015-03-26 23:40:35:363 Kickflip[589:807] Error fetching all streams: Error Domain=kKFAPIClientErrorDomain Code=105 "The operation couldn’t be completed. (kKFAPIClientErrorDomain error 105.)" UserInfo=0x174079480 {success=false, reason='NoneType' object has no attribute '__getitem__'}
2015-03-26 23:40:35:363 Kickflip[589:807] Error fetching all streams: Error Domain=kKFAPIClientErrorDomain Code=105 "Fetch an active user first" UserInfo=0x174271180 {NSLocalizedDescription=Fetch an active user first}

Note:
this issue is report and close on 1.1 for issue #10 , but with latest 1.2 build, I still see this issue

**Comment by 4netinteractive** [comment]
Same error here, yesterday it was working fine.

**Comment by germc** [comment]
Have the same issue, was working earlier this week.

**Comment by 4netinteractive** [comment]
Is there any way to contact Kickflip?

**Comment by germc** [comment]
Yea you can email support@kickflip.uservoice.com , I did over the weekend, just waiting for a response.

**Comment by russwork** [comment]
@germc I did the same. It looks like the server isn't accepting valid app IDs.

**Comment by chrisballinger** [comment]
Hey sorry everybody, we are having some backend issues. Will update when it is resolved.

**Comment by germc** [comment]
Hi Chris, any eta on the fix?  Thanks mate.

**Comment by 4netinteractive** [comment]
Any update? And what about paying customers?

**Comment by Ricardohprc** [comment]
Hi Chris
Looking forward for this update :)
i get the same error

**Comment by jituiitm** [comment]
i got the same error. pls help.

**Comment by BurningBird** [comment]
Hi Chris, it's been a while, any update on this issue? 

Thanks!

**Comment by chrisballinger** [comment]
Should be working again, let me know if you're having any issues.

**Comment by BurningBird** [comment]
Still fails, with a different error though:
2015-04-06 13:01:50:666 Kickflip[4744:807] Error pre-fetching new user: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: forbidden (403)" UserInfo=0x1702e1700 {com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x1742333c0> { URL: https://kickflip.io/api/1.1/user/new } { status code: 403, headers {
    Connection = "keep-alive";
    "Content-Type" = "text/html; charset=utf-8";
    Date = "Mon, 06 Apr 2015 20:01:50 GMT";
    Server = "gunicorn/18.0";
    "Transfer-Encoding" = Identity;
    Via = "1.1 vegur";
} }, NSErrorFailingURLKey=https://kickflip.io/api/1.1/user/new, com.alamofire.serialization.response.error.data=<>, NSLocalizedDescription=Request failed: forbidden (403)}
2015-04-06 13:01:51:042 Kickflip[4744:807] Error fetching all streams: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: forbidden (403)" UserInfo=0x1702e0580 {com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x174229440> { URL: https://kickflip.io/api/1.1/user/new } { status code: 403, headers {
    Connection = "keep-alive";
    "Content-Type" = "text/html; charset=utf-8";
    Date = "Mon, 06 Apr 2015 20:01:50 GMT";
    Server = "gunicorn/18.0";
    "Transfer-Encoding" = Identity;
    Via = "1.1 vegur";
} }, NSErrorFailingURLKey=https://kickflip.io/api/1.1/user/new, com.alamofire.serialization.response.error.data=<>, NSLocalizedDescription=Request failed: forbidden (403)}

**Comment by BurningBird** [comment]
This issue seems only happen with existing app, and went away if I create a new app. Though I am seeing a different issue that failed live streaming, creating another bug.

**Comment by russwork** [comment]
@BurningBird @chrisballinger same issue and same results. I tried hardcoding setupWithAPIKey app/secret, I tried creating a user or logging in with an existing user, etc. I get -1011 403 every time.

**Comment by BurningBird** [comment]
@russwork try create a new app, I had the same issue with existing app, this particular issue should go away with new app. But I am seeing more issues after this, the live streaming just not working. The backend of kickflip is a bit shaky right now.

**Comment by russwork** [comment]
@BurningBird  I got everything to work I think. Blow away everything, do a clean pull, install pods, update pods, clear ~/Library/Developer/Xcode/DerivedData and it seems to work.

**Comment by deshmukhpraveen** [comment]
yesterday worked fine but today is not working.show blow error
Error fetching all streams: Error Domain=kKFAPIClientErrorDomain Code=105 "Fetch an active user first"

**Comment by chrisballinger** [comment]
Hey all, sorry for the delay, we finally fixed the underlying issue that was causing this problem. We exhausted our AWS IAM user limit and needed to slightly rearchitect the backend to use STS tokens instead.

This means you must migrate to the Kickflip iOS SDK v1.3 (aka API 1.2) as soon as possible. No public facing APIs have changed, only some internal S3 logic, so it should be a quick and easy upgrade.

**Comment by deshmukhpraveen** [comment]
*hello Chris,*

*I want to discuss that, I have a plan of kickflip, And my problem is that
after some streaming it shows memory warning and now its not working it
show the warning is mention below...*

1)

Received memory warning.

2015-05-12 19:45:46:259 FitTube[507:3837] Error removing thumbnail: Error
Domain=NSCocoaErrorDomain Code=4 "The operation couldn’t be completed.
(Cocoa error 4.)" UserInfo=0x17f4d5f0 {NSUnderlyingError=0x17f4d280 "The
operation couldn’t be completed. No such file or directory",
NSFilePath=/var/mobile/Containers/Data/Application/0314308F-82D9-4D7D-B274-F4CA1D463389/Documents/998a02bd-aa19-4011-97ed-6a48113d7518.hls/thumb.jpg,
NSUserStringVariant=(

    Remove

)}



And when my streaming is completed i am printing the streaming data and it
shows this


*2) Stream is ready at URL: (null)*



and i also want to streamed video from my account how i delete this...

please provide me proper guidelines.




*Thanks *

*Praveen*

**Comment by chrisballinger** [comment]
@deshmukhpraveen  Have you updated to the latest SDK? Although not ideal, the memory warning shouldn't be a big issue. The error removing the thumbnail is benign and shouldn't affect functionality. As far as the null log statement, did the stream in question work?

To remove a recording, make a POST to `/api/1.2/stream/flag` with the `stream_id` you'd like to remove. 

Also, in the future please make a new issue for each problem instead of posting in an existing issue. Thanks!

**Comment by suyashsadh** [comment]
Hi @deshmukhpraveen i have try but not able to get solution for in this problem please provide another 
solution.
Thanks
Praveen
